### ISSUE TITLE
Expected not to find a document already present for an add error

### ISSUE THREAD

**Issue by dan335** [peerlibrary/meteor-control-mergebox#1]
I'm getting this error on the client.

```
collection.js:163 Uncaught Error: Expected not to find a document already present for an add
```

So how is this package supposed to work?  I add this.disableMergebox(); inside the publish function and everything in Meteor works normally except when the db is changed it sends entire result of the query to the clients instead of only the changes?

**Comment by mitar** [comment]
> I'm getting this error on the client.

Thanks for the report. Can you share to code? Or reproduction, would be even better?

> So how is this package supposed to work? I add this.disableMergebox(); inside the publish function and everything in Meteor works normally except when the db is changed it sends entire result of the query to the clients instead of only the changes?

Yes.

**Comment by mitar** [comment]
(Or, what is the difference between your code and tests.)

**Comment by dan335** [comment]
Here's a repro.  https://github.com/dan335/control-mergebox-error-repro

**Comment by mitar** [comment]
Aaa, on the client side. I missed that one.

**Comment by mitar** [comment]
Hm, but my tests do not have this issue. Let's see what is different.

**Comment by mitar** [comment]
OK, I see what you are doing. You are subscribing multiple times to the same publish function with overlapping documents. And then server side now does not know that it there is already a document on the client side and sends it again, which makes it throw an error on the client side. This is somehow the feature of this package, that the server side does not know about existence.

**Comment by mitar** [comment]
Fixed. Thanks for reporting. Also read the README.
