### ISSUE TITLE
Does this package still work?

### ISSUE THREAD

**Issue by xwilders** [peerlibrary/meteor-control-mergebox#2]
I've been trying to make sense of this package for almost two days now, and I can see no discernable difference between disableMergebox and the default behaviour.

For example when documents call 'added' in a server side observe, successive updates to those documents cause 'changed' to be called. Surely that means there's a mergebox in the background computing differences between documents?

I've even tried manufacturing situations with and without control-mergebox and used Kadira's CPU profiler, but again observed no noticeable difference.

**Comment by mitar** [comment]
> For example when documents call 'added' in a server side observe, successive updates to those documents cause 'changed' to be called

They have to be called, but the difference is that they are called with all fields provided, not only with changed fields provided.

(That is at least the idea, if it is not so, you found a bug.)

> Surely that means there's a mergebox in the background computing differences between documents?

No, it is not.

**Comment by mitar** [comment]
The main difference should be in memory consumption, not necessary CPU consumption.

**Comment by mitar** [comment]
I am closing this for now, if you think it should be reopened, say.
