### ISSUE TITLE
Some questions regarding usability

### ISSUE THREAD

**Issue by theodorDiaconu** [peerlibrary/meteor-control-mergebox#4]
Hi @mitar 

First thanks for doing this, this package is very very cool.

I am planning to integrate this behavior somehow into:
https://github.com/cult-of-coders/redis-oplog

Let me fully grasp the implications of no mergebox. So:

If we have 2 subscriptions in which 2 documents collide, if we want to stop a certain subscription, we cannot simply do a .removed() because it may take it out of the other collection as well, right ?

This means that mergebox would work great with redis-oplog or any other publication, as long as at any given time 2 publications will not expose the same documents.

**Comment by mitar** [comment]
Have you seen discussion in #3.

**Comment by mitar** [comment]
So if you have two subscriptions which collide in a document, then you have two issues:
* overlapping changes to documents
* how to remove them on unsubscribe

> If we have 2 subscriptions in which 2 documents collide, if we want to stop a certain subscription, we cannot simply do a .removed() because it may take it out of the other collection as well, right ?

If they are both with disabled mergebox, then yes.

> This means that mergebox would work great with redis-oplog or any other publication, as long as at any given time 2 publications will not expose the same documents.

Yes, that is the best.

Or, alternatively, we could remember which documents are coming from which subscription on the client and then do some special things on the client. So move more state to the client while server just sends messages of changes to the client. So in some way we change a trade-off here and have more state on the client and more messages on the wire, for less state on the server.

This can probably be done in a backend agnostic manner.

**Comment by theodorDiaconu** [comment]
@mitar thank you for the response, next questions:

https://github.com/peerlibrary/meteor-control-mergebox/blob/master/livedata_server.js

what is the difference here ? between this and:

https://github.com/meteor/meteor/blob/devel/packages/ddp-server/livedata_server.js

What is the purpose for the last line ?

**Comment by mitar** [comment]
There is no difference anymore, I think, because this pull request was merged in: https://github.com/meteor/meteor/pull/5838

**Comment by mitar** [comment]
> What is the purpose for the last line ?

So if you have an old version of Meteor, it copies code there. If you do use a newer version, which already exposes the code, it does not copy it over.

**Comment by mitar** [comment]
And this is only needed because we have to create custom instances of it: https://github.com/peerlibrary/meteor-control-mergebox/blob/71dd33ba1e4e8d088fc046f0322fa7ede70a6bf8/server.coffee

**Comment by theodorDiaconu** [comment]
@mitar got it, thank you very much.

**Comment by mitar** [comment]
Please keep me posted how things are. If you need any changes to this package to make it work for you, also tell.

**Comment by theodorDiaconu** [comment]
Thanks, will keep you posted, I'll come with a PR/questions if necessary.
