### ISSUE TITLE
Are there any performance bottlenecks of disabling mergebox ?

### ISSUE THREAD

**Issue by theodorDiaconu** [peerlibrary/meteor-control-mergebox#5]
Does it have any impact on performance except ofcourse, less memory used ?

**Comment by mitar** [comment]
I mean, all this is trade-off. :-) Less memory used means that it has to send more data through, which means that it consumes CPU for that. But on the other hand, it does not have to do any diffing on the server side, so less CPU for that.

But I have not done any measurements.

This package exists more or less to show how it can be done. I am not using it personally.

**Comment by theodorDiaconu** [comment]
Very nice @mitar thanks.  For what I needed it's just perfect.
