### ISSUE TITLE
[Question] Does this package destroy cached observers/data-sets?

### ISSUE THREAD

**Issue by evolross** [peerlibrary/meteor-control-mergebox#9]
Does using this package also remove the functionality in Meteor that if say 1000 clients all subscribe to the same publication identically, then Meteor caches the observer and data and shares it between the clients thus not querying Mongo 1000 times for the same data?

Is this a functionality of the merge box that would be disabled?

I ask because I have a use-case like the above, but I have zero reactivity or updates needed, so in my publication I only implement `this.added`. I would use a Meteor Method but I want the cached data aspect (reducing load on Mongo).  So disabling the merge box sounds great because I don't have any updates. I've also read that there's something called `SessionCollectionView` that holds _each_ clients subscribed data set in memory which is totally unneeded in my use-case. And with a lot of users could be problematic. But I'm still banking on the server caching of the query result and reduced Mongo load.

**Comment by mitar** [comment]
I would suggest you try out? Create a benchmark and try it. There are many moving pieces here so it is hard to predict what will happen in your case.

**Comment by evolross** [comment]
How would you benchmark this exactly?  I know how to run cloud tests, but that involves deploying on Galaxy and spooling up a bunch of AWS instances.  

Is there some way to test locally with maybe five-ten clients and watch the RAM usage of the node process?  And/or watch queries coming into my local Mongo? I'm a novice with linux tools... any suggestions of where to start?

EDIT: I know one way to test if it's hitting Mongo repeatedly for each client would be to set the publication to polling for like thirty seconds, update the data in Mongo directly, and test if new clients get the old cached data or the fresh data updated in Mongo.

BTW, was just curious if you knew off-hand.

**Comment by mitar** [comment]
I would just measure memory consumption when you make 10, 100, 1000, 10000 clients connect. And I would also enable profiling in mongodb and see how many queries are coming there.
